<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_productCollection = $this->_productCollection; ?>
<div class="homepage-products">
    <?php if ($this->_title != ''): ?>
        <div class="block-title">
            <strong><span><?php echo $this->_title; ?></span></strong>
        </div>
    <?php endif; ?>
    <div class="block-content">
        <?php if(count($_productCollection) > 0): ?>
            <ul>
                <?php $_helper = $this->helper('catalog/output'); ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php $_productNameStripped = strip_tags($_helper->productAttribute($_product, $_product->getName() , 'name')); ?>
                    <li>
                        <div class="product-image">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(75); ?>" width="75" height="75" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        </div>
                        <div class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                        </div>
                        <div class="product-price">
                            <?php echo $this->getPriceHtml($_product, false) ?>
                        </div>
                        <div class="product-add-to-cart">
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php endif; ?>
    </div>
</div>
